version: "3.6"
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
services:
  web:
    build:
      context: .
      dockerfile: ./web_Dockerfile
    depends_on:
      - app
    ports:
      - 9080:80
    networks:
      backend:
        ipv4_address: 192.168.10.4
    volumes:
      - ./doc_root/public:/var/www/sample-app/public

  app:
    build:
      context: .
      dockerfile: ./temp_Dockerfile
    depends_on:
      db:
        condition: service_healthy
    devices:
      - "/dev/i2c-1"
      - "/dev/gpiomem"
    networks:
      backend:
        ipv4_address: 192.168.10.3

  db:
    build:
      context: .
      dockerfile: ./mysql_Dockerfile
    networks:
      backend:
        ipv4_address: 192.168.10.2
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "mysql", "-pmysql"]
      timeout: 20s
      retries: 10

volumes:
  db-data:
    driver: local