version: "3.6"
networks:
    sample-network:
        external: true
services:
  web:
    hostname: app-web
    build:
      context: .
      dockerfile: ./web_Dockerfile
    ports:
      - 9080:80
    networks:
      - sample-network
    volumes:
      - ./doc_root/public:/var/www/sample-app/public

  app:
    hostname: app-temp
    build:
      context: .
      dockerfile: ./temp_Dockerfile
    devices:
      - "/dev/i2c-1"
      - "/dev/gpiomem"
    networks:
      - sample-network

  db:
    hostname: app-db
    build:
      context: .
      dockerfile: ./mysql_Dockerfile
    networks:
      - sample-network

volumes:
  db-data:
    driver: local